//
//  GRVCameraReviewViewController.h
//  Gravvy
//
//  Created by Nnoduka Eruchalu on 5/24/15.
//  Copyright (c) 2015 Nnoduka Eruchalu. All rights reserved.
//

#import <UIKit/UIKit.h>

@class SCRecordSession;

/**
 * GRVCameraReviewViewController provides an interface for reviewing and 
 * processing the record session and preview image generated by 
 * GRVCameraViewController.
 */
@interface GRVCameraReviewViewController : UIViewController

#pragma mark - Properties
#pragma mark Inputs
/**
 * Record session generated by a GRVCameraViewController instance.
 */
@property (strong, nonatomic) SCRecordSession *recordSession;

/**
 * Preview image associated with record session.
 */
@property (strong, nonatomic) UIImage *previewImage;


#pragma mark - Instance Methods
#pragma mark Abstract
/**
 * Recording has been reviewed and user would like to upload the generated
 * mp4 file, with its associated photo, and duration.
 *
 * @param mp4           MP4 data generated from the recording session
 * @param previewImage  Image snapshot representation of the mp4 video
 * @param duration      Length, in seconds, of mp4 video
 */
- (void)completedReviewingRecording:(NSData *)mp4
                       previewImage:(UIImage *)previewImage
                           duration:(NSTimeInterval)duration;

@end
