//
//  GRVCameraReviewViewController.h
//  Gravvy
//
//  Created by Nnoduka Eruchalu on 5/24/15.
//  Copyright (c) 2015 Nnoduka Eruchalu. All rights reserved.
//

#import <UIKit/UIKit.h>

@class SCRecordSession;

/**
 * GRVCameraReviewViewController provides an interface for reviewing and 
 * processing the record session and preview image generated by 
 * GRVCameraViewController.
 */
@interface GRVCameraReviewViewController : UIViewController

#pragma mark - Properties
#pragma mark Inputs
/**
 * Record session generated by a GRVCameraViewController instance.
 */
@property (strong, nonatomic) SCRecordSession *recordSession;

/**
 * Preview image snapshot representation of the record session.
 * This serves as the cover image of the mp4.
 */
@property (strong, nonatomic) UIImage *previewImage;

#pragma mark Outputs
/**
 * MP4 data generated from the recording session
 */
@property (strong, nonatomic) NSData *mp4;


#pragma mark - Instance Methods
#pragma mark Abstract
/**
 * Recording generated a valid mp4 and this has been extracted and displayed
 * to the user in a preview view.
 * This will be a good place to enable the done/next button
 */
- (void)recordingValidated;

@end
